### ISSUE TITLE
Cannot infer type

### ISSUE THREAD

**Issue by Fritiofhedstrom** [TotalKrill/mosquitto_plugin#14]
I get an error when using the plugin at the latest revision:
create_dynamic_library!(ItemBroker);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type

type annotations needed
type must be known at this pointrustc[E0282](https://doc.rust-lang.org/error-index.html#E0282)
dynlib.rs(167, 83): Actual error occurred here

This is the first commit that fails 70b50d490d075b51b17a236bb23adf132dfcd441

**Comment by TotalKrill** [comment]
Solved
