### ISSUE TITLE
1.2.0 Does not follow SemVer

### ISSUE THREAD

**Issue by Fritiofhedstrom** [TotalKrill/mosquitto_plugin#15]
1.2.0 introduces a breaking change in the api. This should be 2.0.0. I suggest publishing a 2.0.0 version to fix it.
https://www.reddit.com/r/rust/comments/x0g0g9/ive_made_a_critical_semver_mistake_can_it_be_fixed/

**Comment by TotalKrill** [comment]
Hey, yes, I noticed as well. 

I will republish and yank 1.3. Thank you for bringing this to my attention. Sorry for the inconvenience
