### ISSUE TITLE
docs.rs is broken

### ISSUE THREAD

**Issue by flxo** [TotalKrill/mosquitto_plugin#18]
The docs.rs for [mosquitto_plugin](https://docs.rs/crate/mosquitto-plugin/2.1.1) is broken because of the missing `mosquitto_broker.h` [dependency](https://docs.rs/crate/mosquitto-plugin/2.1.1/builds/647022).

There is a nice doc how to add a dependency to docs.rs [here](https://forge.rust-lang.org/docs-rs/add-dependencies.html).

**Comment by flxo** [comment]
Unfortunately the `mosquitto_dev` package in Ubuntu 20.04 which is used in [crates-build-env](https://github.com/rust-lang/crates-build-env/blob/527c74c855882523a294cc138e8f133b32da38b2/linux/Dockerfile#L1) contains [mosquitto-dev](https://packages.ubuntu.com/search?keywords=mosquitto&searchon=names&suite=focal&section=all) 1.6.9 which is incompatible with this crate. `crates-build-env` is on Ubuntu LTS and hasn't upgraded to 22.04 yet.

This issues is probably solved when `crates-build-env` upgrades to Ubuntu 22.04 which includes `mosquitto-dev` in version 2.x.x.

**Comment by TotalKrill** [comment]
then we will just wait a bit :)

**Comment by TotalKrill** [comment]
Its now fixed, and this was also 90% of the reason to bump bindgen version :)
