### ISSUE TITLE
Move to use plugin v5 functions.

### ISSUE THREAD

**Issue by Tejpbit** [TotalKrill/mosquitto_plugin#3]
I'd like to be able to listen for disconnects from the broker. As far as I can tell I need to use
[mosquitto_plugin_init](https://mosquitto.org/api/files/mosquitto_plugin-h.html#mosquitto_plugin_init)
That will hand the plugin an _identifier_.
The identifier can then be used with [mosquitto_callback_register](https://mosquitto.org/api/files/mosquitto_broker-h.html#mosquitto_callback_register) to register for MOSQ_EVT_DISCONNECT.

The mosquitto_callback_register support all of these events:
MOSQ_EVT_RELOAD
MOSQ_EVT_ACL_CHECK
MOSQ_EVT_BASIC_AUTH
MOSQ_EVT_EXT_AUTH_START
MOSQ_EVT_EXT_AUTH_CONTINUE
MOSQ_EVT_CONTROL
MOSQ_EVT_MESSAGE
MOSQ_EVT_PSK_KEY
MOSQ_EVT_TICK
MOSQ_EVT_DISCONNECT

These functions are part of the mosquitto plugin v5 interface. We should support that.

The question is should we maintain support for the v4 interface as well?
I don't think we need to since the features of the v5 interface is a superset to that of v4. And I believe the MosquittoPlugin trait can remain the same, with some additions. So we don't need to break the rust api.
So it's just a question of backwards compatibility for older versions of mosquitto.

**Comment by TotalKrill** [comment]
Hmm, I am positive to moving to the v5 interface. I assume we will be able to provide default nop trait implementations for the additions to the MosquittoPlugin trait right?

Also, since I am not aware of that many projects using this library as of yet. I will just update everything I am using currently to support this. Rather have this library remaining relevant, than avoid some minimal update work :)

**Comment by Tejpbit** [comment]
Hey! Back from a bit of vacation. :)

Yupp. Default nop implementations in the trait for the new callback functions, just like the previous bindings did.
I think we'll be able to keep the trait API the same, but we'll see when I get further into implementing it.

**Comment by TotalKrill** [comment]
Hope you had a nice vacation! My campervan broke down on the maiden run, so that was extremely unfortunate, but means i will postpone my vacation. 

Looking forward to seeing the results!
